### ISSUE TITLE
get previous Cilium pod logs

### ISSUE THREAD

**Issue by ianvernon** [cilium/cluster-diagnosis#9]
When running sysdump, we expect to have logs from Cilium pods for the Cilium pods that are currently running, as well as the previous logs for the Cilium pods, provided that such logs exist (i.e., there was a previous instance of that pod running).

**Comment by aanm** [comment]
@ianvernon cluster-diagnosis runs the bug tool here:

https://github.com/cilium/cluster-diagnosis/blob/4958dacb09bf7f623a70d00d7095d88c10953437/cluster-diagnosis/sysdumpcollector.py#L124

which should be the one retrieving the logs from the previous pods

**Comment by ianvernon** [comment]
@aanm bugtool runs inside the Cilium pod, which doesn't have `kubectl` installed in it to get the previous logs. We need to run this from outside the Cilium pod.

**Comment by aanm** [comment]
@ianvernon ohhh that's why then! thanks!

**Comment by ianvernon** [comment]
This functionality is present now, closing.

**Comment by aanm** [comment]
@ianvernon you forgot to click the button to close this ;-)
